### ISSUE TITLE
hi guys . I got problem with react-ts and nextjs when use react-qr-reader : "at t.selectBestPatterns (webpack-internal:///./node_modules/react-qr-reader/" . Please help me know how to fixes . Tks all guys

### ISSUE THREAD

**Issue by tai30101997** [JodusNodus/react-qr-reader#244]
More info :
at t.selectBestPatterns (webpack-internal:///./node_modules/react-qr-reader/dist/esm/index.js:8:222393)
    at t.find (webpack-internal:///./node_modules/react-qr-reader/dist/esm/index.js:8:218235)
    at t.detect (webpack-internal:///./node_modules/react-qr-reader/dist/esm/index.js:8:223801)
    at t.decode (webpack-internal:///./node_modules/react-qr-reader/dist/esm/index.js:8:227258)
    at e.t.decodeBitmap (webpack-internal:///./node_modules/react-qr-reader/dist/esm/index.js:8:355548)

**Comment by fabriceLatri** [comment]
I have the same problem with React 18.1.0 and react-qr-reader 3.0.0-beta-1. Thx for help

**Comment by mdedys** [comment]
This isn't a cause of this repo I believe. Someone has created an issue related to the same topic here: https://github.com/zxing-js/browser/issues/90

**Comment by adrianowy** [comment]
Have you try to use "dynamic import" and setup {ssr:false} ?
Work for me!

**Comment by firstpersoncode** [comment]
> Have you try to use "dynamic import" and setup {ssr:false} ? Work for me!

no it doesn't works for me.

**Comment by adrianowy** [comment]
> > Have you try to use "dynamic import" and setup {ssr:false} ? Work for me!
> 
> no it doesn't works for me.

Could you share your package.json ?

**Comment by yaser-alazm** [comment]
> Have you try to use "dynamic import" and setup {ssr:false} ? Work for me!

Can you explain please what do you mean by dynamic import?

**Comment by SahilAggarwal2004** [comment]
> Have you try to use "dynamic import" and setup {ssr:false} ? Work for me!

Hey, I tried it but it still showing the error :(

**Comment by seongguk-yoon** [comment]
Hello,I have the same problem..
l already  try to use "dynamic import" and setup {ssr:false} 
but it still showing the error :(

please help me know how to fix  :(

**Comment by firaadani** [comment]
I have the same problem. Tried dynamic import with no luck. Any updates on how this issue can be fixed?

The camera runs as it should but it just can't detect the QR
