### ISSUE TITLE
Beta version causing infinite loop, e is undefined 

### ISSUE THREAD

**Issue by iamunadike** [JodusNodus/react-qr-reader#266]
Somehow i noticed when the component is mounted it starts to throw the exception
Something of what I mean is as shown below:

**```
613  

e is undefined
    at t.selectBestPatterns (http://localhost:3000/bundle.js:40796:222393)
    at t.find (http://localhost:3000/bundle.js:40796:218235)
    at t.detect (http://localhost:3000/bundle.js:40796:223801)
    at t.decode (http://localhost:3000/bundle.js:40796:227258)
    at t.decodeBitmap (http://localhost:3000/bundle.js:40796:355548)
    at t.decodeFromCanvas (http://localhost:3000/bundle.js:40796:355663)
    at h (http://localhost:3000/bundle.js:40796:362079)
```**

It just keep looping 613 was the last count of the loop before I stopped it maniually

**Comment by Prasanthcs29** [comment]
Am also getting the same in console, when webcam start scanning

**Comment by adrianowy** [comment]
Try to use the previous version 2.2.0 (https://github.com/react-qr-reader/react-qr-reader/tree/v2.2.0), work for me.

**Comment by codescrafter** [comment]
having same issue

**Comment by avoguga** [comment]
@codescrafter use the last version, but try to use yarn while using the package, apparently the console always will show a error while it cant get a result
