### ISSUE TITLE
Npm test fails

### ISSUE THREAD

**Issue by mattermoran** [JodusNodus/react-qr-reader#35]
Running npm test always fails.

` FAIL  src/App.test.js
  ● renders without crashing

    ReferenceError: Worker is not defined
      
      at Reader.componentDidMount (node_modules/react-qr-reader/lib/index.js:61:25)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:264:25
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:263:11
      at CallbackQueue.notifyAll (node_modules/react-dom/lib/CallbackQueue.js:76:22)
      at ReactReconcileTransaction.close (node_modules/react-dom/lib/ReactReconcileTransaction.js:80:26)
      at ReactReconcileTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:209:25)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:156:16)
      at batchedMountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:126:15)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:143:20)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at Object._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:319:18)
      at Object._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:401:32)
      at Object.render (node_modules/react-dom/lib/ReactMount.js:422:23)
      at Object.<anonymous>.it (src/App.test.js:8:22)
          at Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ✕ renders without crashing (31ms)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.75s
Ran all test suites.
`

**Comment by JodusNodus** [comment]
Not sure what test you are running as there is no test included in the repo. Testing is done manually since it needs a webcam and stuff. Mocking all that would be more work than testing it manual every release.

**Comment by mattermoran** [comment]
Just tried recreating this on the new project.
So first i created new project using create-react-app.
Run npm test and get this: 
<img width="490" alt="screen shot 2017-08-28 at 19 41 17" src="https://user-images.githubusercontent.com/29712386/29772149-f5ea8fdc-8c29-11e7-8819-d04488478b4f.png">
Then i install react-qr-reader and use code from the example. Now if I try npm test i get this:
<img width="803" alt="screen shot 2017-08-28 at 19 47 16" src="https://user-images.githubusercontent.com/29712386/29772190-301512a4-8c2a-11e7-9d54-90e3f68bcec1.png">

Here's the code from npm test:

`import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<App />, div);
});`

**Comment by JodusNodus** [comment]
Aah i see, `react-qr-reader` uses web workers. To create the web worker `new Worker(url)` is used. You could mock that but the module makes use of the web worker extensibly & other browser API's like  WebRTC. It would be much easier to not test the component.

**Comment by mattermoran** [comment]
How to ignore it so test passes?

**Comment by JodusNodus** [comment]
Use shallow rendering (http://airbnb.io/enzyme/docs/api/shallow.html). This way the QR reader component shouldn't be rendered.

**Comment by mattermoran** [comment]
alright, thank a lot for a quick response and the module. It works great for my app!

**Comment by JodusNodus** [comment]
Happy to help, great to hear 👍 .
