### ISSUE TITLE
Help me error selectBestPatterns nobody fix it before (react-qr-reader 3.0.0-beta-1)

### ISSUE THREAD

**Issue by hoaipd** [JodusNodus/react-qr-reader#362]
When I scan QR code, It always return errors
Error:
More info :
`at t.selectBestPatterns (webpack-internal:///./node_modules/react-qr-reader/dist/esm/index.js:8:222393)
at t.find (webpack-internal:///./node_modules/react-qr-reader/dist/esm/index.js:8:218235)
at t.detect (webpack-internal:///./node_modules/react-qr-reader/dist/esm/index.js:8:223801)
at t.decode (webpack-internal:///./node_modules/react-qr-reader/dist/esm/index.js:8:227258)
at e.t.decodeBitmap (webpack-internal:///./node_modules/react-qr-reader/dist/esm/index.js:8:355548)`

**Comment by econtigliani** [comment]
I have the same issue

**Comment by hoaipd** [comment]
> I have the same issue

nobody helps :(

**Comment by avoguga** [comment]
It always return errors, but is working too. 
 
 Try to avoid npm with this package, try to use yarn too.

**Comment by mh-jsx** [comment]
Until the issue got fixed use react-qr-reader@2

or if you have react > 17 Use this instead
https://www.npmjs.com/package/react-zxing

Both the libraries are using @zxing/library under the hood.
