### ISSUE TITLE
Node version Incompatibilty

### ISSUE THREAD

**Issue by Rashmiranjan2001** [JodusNodus/react-qr-reader#367]
I am using node version 12.22.0 and my react is also more than 16 and using react-qr-reader recent version and I am getting this error while running my react app.

/usr/local/lib/node_modules/npmlinks-constants -> /Users/RASHMIRANJAN.ROUT/Downloads/odin2.0/src/constants
/Users/RASHMIRANJAN.ROUT/Downloads/odin2.0/node_modules/npmlinks-constants -> /usr/local/lib/node_modules/npmlinks-constants -> /Users/RASHMIRANJAN.ROUT/Downloads/odin2.0/src/constants
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'resolve'
Require stack:
- /Users/RASHMIRANJAN.ROUT/Downloads/odin2.0/config/webpack.config.js
- /Users/RASHMIRANJAN.ROUT/Downloads/odin2.0/scripts/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/RASHMIRANJAN.ROUT/Downloads/odin2.0/config/webpack.config.js:7:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/RASHMIRANJAN.ROUT/Downloads/odin2.0/config/webpack.config.js',
    '/Users/RASHMIRANJAN.ROUT/Downloads/odin2.0/scripts/build.js'
  ]
}
error Command failed with exit code 1.

while doing yarn install again getting this error.
yarn install v1.22.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error ts-custom-error@3.3.1: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.22.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by miteshdevg** [comment]
https://www.npmjs.com/package/react-qrcode-scanner-mi

use above library
